# Generated by Django 5.1.1 on 2024-09-17 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('discoteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotecas.discoteca')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotecas.servicio')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), name='puntuacion_range')],
            },
        ),
    ]
